# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'GuideMe' do

  # Pods for GuideMe


    pod 'Alamofire', '~> 4.2.0'

end

target 'GuideMeTests' do
    pod 'Alamofire', '~> 4.2.0'
end























